### ISSUE TITLE
Looking for command line feature for generating reports in PNG and PDF.

### ISSUE THREAD

**Issue by chikkalain** [vlsi/ksar#122] opened 2017-11-27 22:06 UTC
In older version , I found report generation in PNG and PDF ,But the new version I did not find these feature. I am looking similar NMON command line fir KSAR also . 

https://nmonvisualizer.github.io/nmonvisualizer/commandline.html

**Comment by chikkalain** [comment] 2017-11-27 22:14
5.0.6 has these feature 

https://en.wikipedia.org/wiki/Ksar_(Unix_sar_grapher)

**Comment by Pitterling** [comment] 2018-02-15 16:15
duplicate of #63

**Closed by Pitterling** 2018-02-15 16:15 UTC
